### ISSUE TITLE
Gemini pro 1.5 support?

### ISSUE THREAD

**Issue by joshiewtf** [small-cactus/M.I.L.E.S#10]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**
Since gemini 1.5 (vertex ai) now has access to function calling, i was wondering if it was possible for it to be implemented on this system.

**Additional context**
Gemini 1.5 has access to OpenAPI Spec function calling like OpenAI, and gemini only requires 1 model for vision and language, rather than openai needing two. You can have a far bigger chat history with context, upload files like pdfs and have access to a better system prompt.
https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling
https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/function-calling
https://cloud.google.com/python/docs/reference/aiplatform/latest/vertexai

to use this you need the `gemini-1.5-pro-preview-0409`.
if it is not possible using the 1.5 model, you can use the `gemini-1.0-pro-001` or `gemini-1.0-pro-002` models respectively.

if needing help with this, e.g: accessing the api, i'd be more than willing to help.

@small-cactus

**Comment by small-cactus** [comment]
From the documentation you provided, the API schema and overall how it
works compared to the OpenAI API is very different. One example is that the
vertex api wants you to list the tool list json inside the function itself,
id have to rewrite the tool logic to implement Gemini support.

If you could prove me wrong and show a more compatible method or a way to
bridge both apis into one easily, that would be great.

**Comment by small-cactus** [comment]
Adding that support would be out of the scope of my skills, I've played around with gemini as a voice assistant and it's not viable, so I don't see value in adding it, there are many reasons, here are some I can name off the top of my head:

All gemini models tend to over explain and don't know when to "shut up". Eg they over explain everything and add extra sentences when not necessary. It'll give you the answer in the first sentence, and then keep talking and talking and talking for like 4 more paragraphs.

Gemini models do not follow instructions very well, they act non deterministic.

Gemini models are trained on VASTLY different training data sets from ChatGPT models, so my entire system prompt would be useless for ideal performance.

Response times are very slow, sometimes it can be fast, but again, they over explain and run time up, a 1 second delay is the difference between a slow reply and thinking that it stopped working.

Believe it or not, OpenAI models are trained to be spoken to, the response format fits perfectly with spoken language, Gemini models are fine in this regard, but it's really not the best. They also don't pay attention to the system instructions enough to understand that I put "You are talking to the user in a voice conversation" into the prompt.

But you are extremely welcome to fork and try to add gemini support, any details you need, I can help with and I will provide them. Here's some stuff to get you started, all tools are located in tools.json, the actual functions to correspond to these arrays are located in main.py randomly within the code (bad I know). The only part you should have to modify is the change AI model function, and "maybe" the change personality function, because it changes the system prompt and I don't know if the format is the same.

Other than that, all openai code (besides webcam recognition) is within the ask function. Let me know if you need anything else!

**Comment by small-cactus** [comment]
I think im gonna use groq's API as they have native function calling support using OpenAI's schema for other models
