### ISSUE TITLE
Setup does not save to apikey.py

### ISSUE THREAD

**Issue by MangoTigers** [small-cactus/M.I.L.E.S#12]
**Describe the bug**
i tried starting it up but it gets stuck on setup no matter how many times i setup or launch it every time i skipped the home assistance page. i opened the apikey.py file and put it in manually and put the home assistant settings as "skip" and it launched.

**Desktop (please complete the following information):**
 - OS: windows 11 home insider preview
 - Version 22H2

**Comment by newideas99** [comment]
Same issue here! I put home assistant settings as "none" and it launched. 

But ya its not saving api keys with the current setup.

**Comment by small-cactus** [comment]
The issue is that I have the amount of setup steps set to the amount that home assistant requires, without logic to default back to the number that it requires without home assistant. 

To fix the issue temporarily, you can manually save your apikeys in `apikey.py`, make sure you set the home assistant ones to random numbers, or open `renderer.js` and search for: 

`const totalInputs = 7;`

and change `7` to `5`.

Then go through setup like normal and it should work, but I'm not entirely sure

Please update me if this temp fix solves the issue.

**Comment by small-cactus** [comment]
I've pushed a final fix, if one of you in this issue could try it out and let me know if it works, that would be great.
