### ISSUE TITLE
Tfile runtime only supported on Linux and not MacOS

### ISSUE THREAD

**Issue by newideas99** [small-cactus/M.I.L.E.S#15]
**Describe the bug**

Python Error: WARNING:root:Tried to import the tflite runtime, but it was not found. Trying to switching to onnxruntime instead, if appropriate models are available.

tflite_runtime is only supported on linux and not MacOS.
<img width="857" alt="image" src="https://github.com/small-cactus/M.I.L.E.S/assets/56652858/e6da47a2-2b41-4bbb-bb54-8bca182dc175">

MILES does switch to the onnxruntime, but the python error causes MILES to not show conversation history in electron. 

**To Reproduce**
1. Run through the full setup on MacOS.
2. npm start
3. 
<img width="607" alt="image" src="https://github.com/small-cactus/M.I.L.E.S/assets/56652858/f7541515-6572-4519-80af-3e033ccb970a">

**Expected behavior**
Miles should start up and show the conversation history as i talk to it. 

**Laptop **
 - Mac OS M1 Pro

**Additional context**
My fix was to change the code in main.py:
```
if platform.system() == 'Windows' or 'Darwin':
    MODEL_PATH = "Miles/miles-50k.onnx"
    INFERENCE_FRAMEWORK = 'onnx'
    DETECTION_THRESHOLD = 0.01

```

I didn't want to do a pull request incase i'm just missing something.

**Comment by small-cactus** [comment]
The tflite wake word model file performs better on Mac rather than the onnx file type.

Each file type also highly depends on your audio setup and environment, onnx might work better for you specifically, or there might be no difference, but in my testing in a few different environments, tflite always had less unintended activations and more intended activations than the onnx file type.

Another issue I had with the different file types is that the detection thresholds are completely arbitrary when switching between them.

Typically the issue you're describing is mitigated by the error message just going away after you talk to Miles, for that specific error, and the history is resumed. In my testing on windows and Mac it always uses tflite on Mac, and onnx on windows without issues or error messages so I'm not sure why history doesn't resume for you, I assume it's a Mac issue because you're missing the tensor flow lite package.

If you have any other issues or questions I'd be glad to help!

**Comment by small-cactus** [comment]
Follow-up, I read the issue more carefully and I see you mentioned tensorflow lite is not a package for Mac, I assumed the full Tensorflow library included it as a module, but I know I also installed the source file directly for tf lite, so I'll update the code later to check for tf lite, and it not available I'll have it use onnx.

Thank you for reporting this!
