### ISSUE TITLE
Getting an error right after completing setup.

### ISSUE THREAD

**Issue by Umbeto** [small-cactus/M.I.L.E.S#4]
I have tried it `many` times and right after i complete the setup with the api stuff i get an error message like this:
![image_2024-03-08_223650379](https://github.com/small-cactus/M.I.L.E.S/assets/97898637/fa740514-1f7c-4e74-bb00-e53f7c3aba44)

Does anyone know why this is happening?

**Comment by small-cactus** [comment]
It happens because the server used for miles is already running somewhere, and the miles server cannot overtake it so it fails, here is how you fix it, if it doesn't work, a computer restart will fix it.

1. Open the Command Prompt as an administrator.

2. To find the process ID (PID) using the port, type:
```
netstat -ano | findstr :3000
```
3. Identify the PID associated with port 3000 from the output.
4. To terminate the process, use:
```
taskkill /PID <PID> /F
```
5. Now you can reopen the while in the directory, use:
```
npm start
```

**Example:** It should look like this when you run the commands:

```bash
C:\> netstat -ano | findstr :3000
  TCP    0.0.0.0:3000           0.0.0.0:0              LISTENING       1234 
#                                           copy whatever this number is ^

C:\> taskkill /PID 1234 /F
#then paste it here ^
SUCCESS: The process with PID 1234 has been terminated.

C:\> 
```

**Comment by Umbeto** [comment]
That seems to fix that issue but now when i run the Setup.sh i get an error that only shows up for a moment but i managed to screenshot it
![image](https://github.com/small-cactus/M.I.L.E.S/assets/97898637/2af9477b-d73d-41e5-add1-f3987a3681fa)
I also cant talk to miles and that bubble in the top left corner that is supposed to say "Listening for Miles" is empty im not an expert on python but im guessing the error has something to do with that.

**Comment by small-cactus** [comment]
Setup.sh is meant for MacOS only, you should be double clicking the file that says `Setup.bat`.

As for the missing imports in the second image, they ***should*** be installed when you run Setup.bat correctly. But sometimes it doesn't work right because it's windows, and it never works right.

To install all of the missing imports you should open CMD and paste this command, it doesn't matter what directory you are in:
```bash
pip install wheel
```

***Then run:***
```bash
pip install requests openai spotipy SpeechRecognition gTTS pydub PyAudio pvporcupine socketio winsound platform sympy
```

Then when they all finish downloading, you should be able to run Miles using the command to run it as before (while in the correct directory).

```bash
npm start
```

**Comment by small-cactus** [comment]
I preformed a clean install on a virtual windows machine, it turns out there are several flaws to the windows install file.

I updated the file, you can download just the new `setup.bat` from my current GitHub page and paste it directly into the Miles-V2 folder and click replace when prompted.

I also had to run these commands, I am not sure if you will have to run them:

```bash
python -m pip install --upgrade pip setuptools wheel
```

I also had to manually install each dependency one at a time, for some unknown reason.

```bash
pip install requests
pip install openai
pip install spotipy
pip install SpeechRecognition
pip install gTTS
pip install pydub
pip install PyAudio
pip install pvporcupine
pip install socketio
pip install sympy
pip install setuptools
```

**Comment by Umbeto** [comment]
Thanks i will try it now :D

**Comment by small-cactus** [comment]
It sounds like you're using the old setup.bat file, the new one doesn't install winsound and also installs electron before trying to run the app. socketio should install correctly in the new setup.bat. 

The command that fixed the socketio install for me, was this:
```bash
python -m pip install --upgrade pip setuptools wheel
```
Run that command, then run the setup file using 
```bash
./setup.bat
```

If it STILL doesn't work, and says you are missing imports for some ungodly reason (I hate windows) then you need to delete and reinstall every module individually.

Please run this, it will delete cached downloaded from pip and let you install new ones fresh.
```bash
pip cache purge
```

You can then install each module separately, copy each line and paste it in terminal one by one clicking enter after each one and waiting for it to finish installing:

```bash
pip install requests
pip install openai
pip install spotipy
pip install SpeechRecognition
pip install gTTS
pip install pydub
pip install PyAudio
pip install pvporcupine
pip install socketio
pip install python-socketio
pip install sympy
pip install setuptools
```

**Comment by Umbeto** [comment]
Yeah i downloaded the file again and tried it but it still doesnt work im not sure if i have the new setup.bat file or the old one, I tried reinstalling it multiple times but it doesnt seem to work. Is there something i need to do after i install the new file?
![image](https://github.com/small-cactus/M.I.L.E.S/assets/97898637/2960a75b-ab17-47c0-80a6-25c55774a30f)
`python -m pip install --upgrade pip setuptools wheel`  didnt work either

**Comment by small-cactus** [comment]
From the tiny part of the file path at the bottom, I can tell you aren't in a virtual environment. These are the instructions to install it on windows, from the top with nothing else needed:

https://github.com/small-cactus/M.I.L.E.S/wiki/Install-Miles-On-Windows


You can delete all of your folders and files from anything you've installed (the M.I.L.E.S folder), the guide will install everything correctly, and if it's already installed, it won't install it twice.

Make sure you follow the guide closely, I had an issue where I was in another instance of the Miles folder, after installing the new one, and it didn't work until I completely followed the guide.
